services:
  - type: web
    name: pa-intel-api
    runtime: python
    repo: https://github.com/Rahul268/pa-intel-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11.0"
